#!/bin/bash
set -u
set -e

trap 'echo "ERROR: Abnormal exit." >&2' ERR

function usage() {
	cat >&2 <<END
Usage: $0 FQDN_host DocumentRoot
Example: $0 test.example.com /var/www

Validate the hostname "FQDN_host".
Once a hostname is validated, you can issue an SSL certificate for it.

A filename is created in the directory "DocumentRoot". It contains the StartSSL challenge code.
You must have a running web server which serves from "DocumentRoot".
The "FQDN_host" must be pointed by DNS to this web server's IP address.
END
	exit 1
}

if [ "$#" -ne 2 ]; then
	usage
fi

HOST_FULL="$1" ; shift
WWW_DIR="$1" ; shift

. "$STARTSSL_CLI_ROOT/config"
. "$STARTSSL_CLI_ROOT/scripts/helper.inc"

if [ ! -d "$WWW_DIR" ]; then 
	echo "DocumentRoot dir $WWW_DIR is missing"
	usage
fi

echo "DBG: ApplyWebControl..."
cli tokenID="$CFG_TOKEN_ID" actionType=ApplyWebControl hostname="$HOST_FULL" 2>/dev/null

if [ "${_CLI_RET['status']}" -ne 1 ]; then
	# StartSSL disagree
	if [ "${_CLI_RET['errorCode']}" -eq "-13" ]; then
		# The domain is already validated
		echo "The domain $HOST_FULL is already validated."
		echo "Server responded: ${_CLI_RET['shortMsg']}"
		exit 0
	else
		echo "CLI error!" >&2
		dump_cli_ret >&2
		exit 1
	fi
fi

CODE="${_CLI_RET['data']}"
CODE_FILE="$WWW_DIR/${HOST_FULL}.html"

echo "$CODE" > "$CODE_FILE"

# this may take some time
echo "DBG: WebControlValidation..."
cli --ignore-api-status tokenID="$CFG_TOKEN_ID" actionType=WebControlValidation hostname="$HOST_FULL"
rm "$CODE_FILE"

if [ "${_CLI_RET['status']}" -ne 1 ]; then
	echo "CLI error!" >&2
	dump_cli_ret >&2
	exit 1
fi

echo "DBG: All done."
